### PR TITLE
New IGraphMap

### PR DESCRIPTION
**Pull request by nreinicke**
Some updates to try to improve the memory efficiency of the road maps:
 - updates the `NxMap` to not keep duplicate records of the roads and rather build roads "on the fly" from the underlying graph object.
 - adds a new `IGraphMap` based on the igraph library.

### CODE REVIEW

**Comment by nreinicke** [comment]
@jhoshiko - do you mind taking a look at this whenever you get a chance?

**Comment by jhoshiko** [comment]
@nreinicke I'm currently testing this with the Amazon work. Once the pipeline is done, I think it will be a good test.

**Review by jhoshiko — CHANGES_REQUESTED** [review]
Sorry about the delay. It's been a bit hectic the last few days!

Everything looks good in this PR and the new `IGraph` seems to be working in our other projects. However, when I went to test the default `NxGraph`, I'm unable to load road networks from TomTom because NxGraph does not have a `from_nx_graph` method. In the mappymatch-nrel repo, the TomTom reader function `read_tomtom_nxmap_from_sql` tries to use this method to create an NxMap resulting in an error.

We could resolve this by either adding a `from_nx_graph` method to `NxMap` or we could tweak the `read_tomtom_nxmap_from_sql` in mappymatch-nrel.

**Comment by nreinicke** [comment]
> the TomTom reader function read_tomtom_nxmap_from_sql tries to use this method to create an NxMap resulting in an error.

Oh right, good catch! I think my vote would be to just modify the `read_tomtom_nxmap_from_sql` function to just use the default constructor `NxMap(nx_graph)`.

**Review by jhoshiko — APPROVED** [review]

**Comment by jhoshiko** [comment]
Awesome! Sounds good to me!

**Pull request merged**
