### PR TITLE
Start versioning

### PR DESCRIPTION
**Pull request by Rowlando13**

### CODE REVIEW

**Comment by Rowlando13** [comment]
Added sphinx-autobuild to make updating docs easier. Basically autoreload upon save. 
Added tbump. To update the version in all places run tbump <new_version> --only-patch

**Review by nreinicke — COMMENTED** [review]
Nice, `tbump` is pretty slick.

We probably also want to add it as a dev dependency [here](https://github.com/NREL/mappymatch/blob/d1e80d54aa999f0f2bf3a664bdcde438928ee33b/setup.py#L56)

And, we probably want to add sphinx-autobuild to the [doc section](https://github.com/NREL/mappymatch/blob/d1e80d54aa999f0f2bf3a664bdcde438928ee33b/setup.py#L50)

Then, we should check in the new pinned dev requirements: `pip-compile requirements-dev.in`

**Comment by Rowlando13** [comment]
I have a PR to move us to a py project.toml. It is not done yet. There are some other missing dependencies that I found when I was working on that branch. I would rather fix it on that one.

**Comment by Rowlando13** [comment]
I fixed tbump issue on the other branch.

**Review by nreinicke — APPROVED** [review]
That works for me, thanks for adding this in!

**Pull request merged**
