### PR TITLE
Check in example notebook from other repo

### PR DESCRIPTION
**Pull request by machallboyd**
Addresses issue #27 

 Bring in the notebook from the other repository

Before approving, a reviewer should verify that the new instructions work correctly on machines that aren't mine.

### CODE REVIEW

**Comment by machallboyd** [comment]
This should go to the examples folder

**Review by Rowlando13 — COMMENTED** [review]
Changes look good.

**Comment by jakeholden** [comment]
Planning to create a `NREL/mappymatch-examples` repo to hold all notebooks and example code.

**Comment by Rowlando13** [comment]
Going to put into a separate repo called mappymatch_examples.

**Comment by nreinicke** [comment]
I've just added this notebook to a new repository here: https://github.com/NREL/mappymatch-examples. Sorry for the duplicate work, thanks for helping us out!

**Pull request closed without merging**
