### PR TITLE
Moving function into class method.

### PR DESCRIPTION
**Pull request by Rowlando13**
Add examples and cleanup inconsistencies in code base.

### CODE REVIEW

**Comment by Rowlando13** [comment]
I am going through will the goal of making our examples repository more robust. I came upon a design pattern that seemed inconsistent but did not want to change and deprecate without input. The geofence_from_trace function seems like it should be a class method and that the Geofence class should be a full class instead of a named tuple. For example the Trace class has a lot of .from.. methods to help with its creation from a bunch of formats.

**Comment by nreinicke** [comment]
@Rowlando13 - sorry for the late reply but I agree with your idea of moving the `geofence_from_trace` method into a class method on the `Geofence` class. I also like the idea of making the `Geofence` a generic class since it really doesn't need to inherit from a NamedTuple.

**Comment by Rowlando13** [comment]
No worries on the time delay. I did not work on anything for 6 weeks when I was busy. Life happens. Sounds good to me.

**Comment by Rowlando13** [comment]
Moved functions into class methods. Made constants in UPPER_CASE. Updated docs. Finally got some time and finished this. The docs are a lot better. Did not get to the examples but will do that on another branch.

**Comment by Rowlando13** [comment]
@nreinicke . Finally ready for review.

**Review by Rowlando13 — COMMENTED** [review]
Reviewed.

**Comment by Rowlando13** [comment]
Also, I have a pypi account and the packaging is setup for another release. So if you give me permissions, I will release it on pypi.

**Review by nreinicke — APPROVED** [review]
This looks great, thanks for doing this!

**Pull request merged**
