### PR TITLE
Add install instructions to docs

### PR DESCRIPTION
**Pull request by nreinicke**
Fills out the install section of the docs and updates the README to link to this updated section (rather than duplicating the information).

### CODE REVIEW

**Comment by nreinicke** [comment]
Closes #56

**Comment by Rowlando13** [comment]
I would have implemented this PR differently: 

- On the README, I would only have the build from the source instructions and link to documentation for full install instructions. We expect some people to have trouble with Pip, so I don't think we should lead with that. Once we get the package on Conda, then we can replace build from the source with conda install instructions.
- In the install docs, I would lead with build from source, then conda (with a note about it being forthcoming), then pip with the warnings. Build from the source first since it is most likely to work since it is really just a conda install. Then conda and pip since they both have problems. One being that we have not implemented it yet and the other being tough dependency installs for windows. 
- I would have used #. for the numbering in lists since it autonumbers. 

That being said, I am interested in your thoughts.

**Comment by nreinicke** [comment]
@Rowlando13 - this is good feedback. Ultimately I would like the package to be easy to install via pip and so we could just lead with that but we're not quite there yet. I've revised the README to just link directly to the docs and I've lead with installation from source. Let me know what you think.

**Review by Rowlando13 — APPROVED** [review]

**Comment by Rowlando13** [comment]
I meant to say this before, it is really nice to have another person work on documentation. I looked at the changes. Another finer point about restructured text, you used ^^^^^ for breaking the sections, but the [python style guide](https://www.sphinx-doc.org/en/master/usage/restructuredtext/basics.html#sections) says to use -----------. Sphinx does not actually care. As you noticed, it generated valid sections. I think we should standardize now to make it easier for contribution down the line.

**Review by machallboyd — APPROVED** [review]
Looks like clear changes.

**Comment by nreinicke** [comment]
@Rowlando13 @machallboyd - thanks for the review!

@Rowlando13 - I like the idea of standardizing the documentation format and so I went ahead and updated that in b0a112f4148e9dab383848c19f9cf437e9cdc5f0

**Pull request merged**
